# Generated by Django 5.0.3 on 2024-05-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
    ]
