# Generated by Django 5.0.4 on 2024-04-07 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to='User.user')),
            ],
            bases=('User.user',),
        ),
    ]
