# Generated by Django 5.0.4 on 2024-04-07 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Local', '0001_initial'),
        ('Manager', '0001_initial'),
        ('Organisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('etat', models.CharField(choices=[('EC', 'En Cours'), ('ACC', 'Accepté'), ('REF', 'Refusé')], default='EC', max_length=3)),
                ('types', models.CharField(choices=[('JRS', 'Journée'), ('RD', 'Remise des diplômes'), ('SP', 'Spectacles'), ('FR', 'Foires'), ('CRV', 'Carnaval'), ('CRC', 'Concours'), ('SRT', 'Sorties'), ('FETE', 'Fête'), ('SM', 'Semaine'), ('CMP', 'Campagnes')], default='JRS', max_length=4)),
                ('besoin', models.CharField(max_length=255)),
                ('commite', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255)),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='Local.local')),
                ('man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='Manager.manager')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='Organisateur.organisateur')),
            ],
        ),
    ]
