# Generated by Django 5.0.4 on 2024-05-15 10:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='types',
            field=models.CharField(choices=[('OH', 'Open House'), ('GC', 'Graduation Ceremony'), ('PP', 'Performances and Plays'), ('CD', 'Cultural Days'), ('CF', 'Career Fairs'), ('ScD', 'Science Day'), ('ACC', 'Academic Competitions'), ('SC', 'School Carnival'), ('AW', 'Awareness Week'), ('EFT', 'Educational Field Trips'), ('SF', 'School Festival'), ('BW', 'Book Week'), ('SpD', 'Sports Day'), ('TW', 'Talent Week'), ('AWC', 'Awareness Campaigns')], default='CD', max_length=4),
        ),
    ]
