# Generated by Django 5.0.3 on 2024-05-18 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0002_alter_demande_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='demande',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
