# Generated by Django 5.0.4 on 2024-05-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0003_demande_end_date_demande_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
